import {
  ArrowRight,
  BookOpen,
  Briefcase,
  Building,
  Building2,
  Calendar,
  CalendarCheck,
  CalendarClock,
  CheckSquare,
  ClipboardList,
  Clock,
  CreditCard,
  Crosshair,
  DollarSign,
  Facebook,
  FileBarChart,
  FileSignature,
  FileText,
  GitBranch,
  GitMerge,
  Globe,
  IdCard,
  LayoutDashboard,
  LayoutPanelTop,
  ListChecks,
  MapPin,
  Megaphone,
  Newspaper,
  Package,
  PackageCheck,
  Percent,
  Receipt,
  RefreshCw,
  RotateCw,
  ScrollText,
  Settings,
  ShieldCheck,
  ShoppingCart,
  Shuffle,
  SlidersHorizontal,
  Star,
  Target,
  TrendingUp,
  Truck,
  Undo2,
  UserCheck,
  UserPlus,
  Users,
  Workflow,
  Wrench,
  Zap,
} from 'lucide-react';
import { ROUTES } from '@/app/router/route-paths';

/**
 * The CRM section of the sidebar, and the CRM section of the mobile "More" sheet.
 *
 * It lives here rather than in DashboardLayout so that reading it does not mean
 * importing the layout: `crm-nav-coverage.test.ts` checks this list against the route
 * table, and a non-component export from a component module also costs Fast Refresh.
 */
export const crmNav = [
  { label: 'Leads', href: ROUTES.dashboard.crmLeads, icon: Users },
  { label: 'Contacts', href: ROUTES.dashboard.crmContacts, icon: UserCheck },
  { label: 'Duplicates', href: ROUTES.dashboard.crmDedup, icon: GitMerge },
  { label: 'Deals', href: ROUTES.dashboard.crmDeals, icon: Briefcase },
  { label: 'Pipelines', href: '/dashboard/crm/pipelines', icon: GitBranch },
  { label: 'Approvals', href: '/dashboard/crm/approvals', icon: ShieldCheck },
  { label: 'Organisations', href: ROUTES.dashboard.crmOrganizations, icon: Building2 },
  { label: 'Accounts', href: ROUTES.dashboard.crmAccounts, icon: Building },
  { label: 'Nurture', href: ROUTES.dashboard.crmNurture, icon: Workflow },
  { label: 'Outreach', href: ROUTES.dashboard.crmCampaigns, icon: Megaphone },
  // Analytics and Support are deliberately absent here: both live once, in the primary rail, as
  // the unified pages. The CRM-only routes still resolve for anyone with a bookmark.
  { label: 'Tasks', href: ROUTES.dashboard.crmTasks, icon: CheckSquare },
  { label: 'Quotes', href: ROUTES.dashboard.crmQuotes, icon: FileText },
  { label: 'Proposals', href: ROUTES.dashboard.crmProposals, icon: ClipboardList },
  { label: 'Invoices', href: ROUTES.dashboard.crmInvoices, icon: Receipt },
  { label: 'Subscriptions', href: ROUTES.dashboard.crmSubscriptions, icon: RefreshCw },
  { label: 'Sales orders', href: ROUTES.dashboard.crmOrders, icon: Package },
  { label: 'Meetings', href: ROUTES.dashboard.crmMeetings, icon: CalendarCheck },
  { label: 'NPS', href: ROUTES.dashboard.crmNps, icon: Star },
  { label: 'Time Tracking', href: ROUTES.dashboard.crmTimeTracking, icon: Clock },
  { label: 'Custom Fields', href: ROUTES.dashboard.crmCustomFields, icon: SlidersHorizontal },
  { label: 'Automations', href: ROUTES.dashboard.crmWorkflows, icon: Zap },
  { label: 'Automated campaigns', href: '/dashboard/crm/workflow-campaigns', icon: Target },
  { label: 'Meta ads', href: '/dashboard/crm/meta-ads', icon: Facebook },
  { label: 'Announcements', href: ROUTES.dashboard.crmAnnouncements, icon: Newspaper },
  { label: 'Processes', href: ROUTES.dashboard.crmProcessTasks, icon: ListChecks },
  { label: 'Event Tracking', href: ROUTES.dashboard.crmEventIngestion, icon: Globe },

  // ── After-sales, procurement and the shared inbox (from AfterSales) ──
  { label: 'Deals hub', href: ROUTES.dashboard.crmDealsHub, icon: Briefcase },
  { label: 'Shared inbox', href: ROUTES.dashboard.crmInbox, icon: LayoutDashboard },
  { label: 'Return authorisations', href: ROUTES.dashboard.crmReturns, icon: RotateCw },
  { label: 'Work orders', href: ROUTES.dashboard.crmWorkOrders, icon: Wrench },
  { label: 'Vendors', href: ROUTES.dashboard.crmVendors, icon: Truck },
  { label: 'Purchase orders', href: ROUTES.dashboard.crmPurchaseOrders, icon: ShoppingCart },
  { label: 'Goods receipts', href: ROUTES.dashboard.crmGoodsReceipts, icon: PackageCheck },
  { label: 'Supplier invoices', href: ROUTES.dashboard.crmSupplierInvoices, icon: CreditCard },
  { label: 'Customer onboarding', href: ROUTES.dashboard.crmCustomerOnboarding, icon: UserPlus },
  { label: 'Ops dashboard', href: ROUTES.dashboard.crmOpsDashboard, icon: LayoutDashboard },
  { label: 'Time periods', href: ROUTES.dashboard.crmTimePeriods, icon: Calendar },
  { label: 'Approval chains', href: ROUTES.dashboard.crmApprovalChains, icon: ArrowRight },
  { label: 'Assignment rotation', href: ROUTES.dashboard.crmAssignmentRotation, icon: Shuffle },
  { label: 'Activity feed', href: ROUTES.dashboard.crmActivity, icon: Globe },
  { label: 'Audit log', href: ROUTES.dashboard.crmAudit, icon: ScrollText },
  { label: 'Notification settings', href: ROUTES.dashboard.crmNotificationSettings, icon: Settings },
  // ── Routed but previously unlinked: reachable only by typing the URL until now.
  // Analytics and Support stay out on purpose — see the note above; they live once
  // in the primary rail as the unified pages. ──
  { label: 'Contracts', href: ROUTES.dashboard.crmContracts, icon: FileSignature },
  { label: 'Renewals', href: ROUTES.dashboard.crmRenewals, icon: CalendarClock },
  { label: 'Price books', href: ROUTES.dashboard.crmPriceBooks, icon: BookOpen },
  { label: 'Competitors', href: ROUTES.dashboard.crmCompetitors, icon: Crosshair },
  { label: 'Territories', href: ROUTES.dashboard.crmTerritories, icon: MapPin },
  { label: 'Web forms', href: ROUTES.dashboard.crmWebForms, icon: Globe },
  { label: 'Deliveries', href: ROUTES.dashboard.crmDeliveries, icon: Truck },
  { label: 'Inventory', href: ROUTES.dashboard.crmInventory, icon: Package },
  { label: 'Bundles', href: ROUTES.dashboard.crmProductBundles, icon: Package },
  { label: 'Credit notes', href: ROUTES.dashboard.crmCreditNotes, icon: Undo2 },
  { label: 'Payment terms', href: ROUTES.dashboard.crmPaymentTerms, icon: Calendar },
  { label: 'Tax rules', href: ROUTES.dashboard.crmTaxRules, icon: Percent },
  { label: 'Commissions', href: ROUTES.dashboard.crmCommissions, icon: DollarSign },
  { label: 'Knowledge base', href: ROUTES.dashboard.crmKnowledgeBase, icon: BookOpen },
  { label: 'Reports', href: ROUTES.dashboard.crmReports, icon: FileBarChart },
  { label: 'Dashboards', href: ROUTES.dashboard.crmDashboards, icon: LayoutPanelTop },
  { label: 'Scoring rules', href: ROUTES.dashboard.crmScoringRules, icon: TrendingUp },
  { label: 'Feature settings', href: ROUTES.dashboard.crmFeatureSettings, icon: SlidersHorizontal },
  { label: 'Contact cards', href: '/dashboard/crm/contact-cards', icon: IdCard },
  { label: 'Equipment', href: '/dashboard/crm/equipment', icon: Wrench },
];
