export const ROUTES = {
  auth: {
    login: '/auth/login',
    register: '/auth/register',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
    verifyEmail: '/verify-email',
  },
  public: {
    acceptInvitation: '/accept-invitation',
    approval: (runId: string) => `/approvals/${runId}`,
  },
  dashboard: {
    root: '/dashboard',
    // ── Chat-first primary surfaces (new) ──
    chat: '/dashboard/chat',
    home: '/dashboard/home',
    // ── Existing pages (still reachable, still routed) ──
    // NOTE: setup + onboarding kept for the type, but their routes are
    // commented out in routes.tsx since chat-first replaces them. Don't
    // link to them in new code.
    setup: '/dashboard/setup',
    settings: '/dashboard/settings',
    team: '/dashboard/team',
    intents: '/dashboard/intents',
    intentDetail: (id: string) => `/dashboard/intents/${id}`,
    apiSpecs: '/dashboard/api-specs',
    apiSpecDetail: (id: string) => `/dashboard/api-specs/${id}`,
    apiConnection: '/dashboard/api-connection',
    apiConnectionDetail: (specId: string) => `/dashboard/api-connection/${specId}`,
    intentSuggestions: '/dashboard/intent-suggestions',
    catalog: '/dashboard/catalog',
    businessCatalog: '/dashboard/business-catalog',
    flows: '/dashboard/flows',
    botSettings: '/dashboard/bot-settings',
    channels: '/dashboard/channels',
    testChannel: '/dashboard/test-channel',
    conversations: '/dashboard/conversations',
    campaigns: '/dashboard/campaigns',
    campaignNew: '/dashboard/campaigns/new',
    agents: '/dashboard/agents',
    analytics: '/dashboard/analytics',
    onboarding: '/dashboard/onboarding',
    // ── CRM ──
    crmLeads: '/dashboard/crm/leads',
    crmLeadDetail: (id: string) => `/dashboard/crm/leads/${id}`,
    crmContacts: '/dashboard/crm/contacts',
    crmContactDetail: (id: string) => `/dashboard/crm/contacts/${id}`,
    crmOrganizations: '/dashboard/crm/organizations',
    crmAccounts: '/dashboard/crm/accounts',
    crmDealsHub: '/dashboard/crm/deals-hub',
    crmDeals: '/dashboard/crm/deals',
    crmDealDetail: (id: string) => `/dashboard/crm/deals/${id}`,
    crmPipelines: '/dashboard/crm/pipelines',
    crmNurture: '/dashboard/crm/nurture',
    crmCampaigns: '/dashboard/crm/campaigns',
    crmAnalytics: '/dashboard/crm/analytics',
    crmAuditLog: '/dashboard/crm/audit-log',
    crmFeatureSettings: '/dashboard/crm/feature-settings',
    crmSupport: '/dashboard/crm/support',
    crmTasks: '/dashboard/crm/tasks',
    crmQuotes: '/dashboard/crm/quotes',
    crmProposals: '/dashboard/crm/proposals',
    crmInvoices: '/dashboard/crm/invoices',
    crmCreditNotes: '/dashboard/crm/credit-notes',
    crmSubscriptions: '/dashboard/crm/subscriptions',
    crmRenewals: '/dashboard/crm/renewals',
    crmTaxRules: '/dashboard/crm/tax-rules',
    crmPriceBooks: '/dashboard/crm/price-books',
    crmPaymentTerms: '/dashboard/crm/payment-terms',
    crmInventory: '/dashboard/crm/inventory',
    crmProductBundles: '/dashboard/crm/product-bundles',
    crmReports: '/dashboard/crm/reports',
    crmDashboards: '/dashboard/crm/dashboards',
    crmKnowledgeBase: '/dashboard/crm/knowledge-base',
    crmContracts: '/dashboard/crm/contracts',
    crmContractTemplates: '/dashboard/crm/contract-templates',
    crmOrders: '/dashboard/crm/orders',
    crmDeliveries: '/dashboard/crm/deliveries',
    crmMeetings: '/dashboard/crm/meetings',
    crmWorkflows: '/dashboard/crm/workflows',
    crmNps: '/dashboard/crm/nps',
    crmScoringRules: '/dashboard/crm/scoring-rules',
    crmCompetitors: '/dashboard/crm/competitors',
    crmTimeTracking: '/dashboard/crm/time-tracking',
    crmCustomFields: '/dashboard/crm/custom-fields',
    crmDedup: '/dashboard/crm/dedup',
    crmAnnouncements: '/dashboard/crm/announcements',
    crmProcessTasks: '/dashboard/crm/process-tasks',
    crmProcessDefinitions: '/dashboard/crm/process-definitions',
    crmProcessInstances: '/dashboard/crm/process-instances',
    crmEventIngestion: '/dashboard/crm/event-ingestion',
    crmInbox: '/dashboard/crm/inbox',
    crmActivity: '/dashboard/crm/activity',
    crmAudit: '/dashboard/crm/audit',
    crmNotificationSettings: '/dashboard/crm/notification-settings',
    crmReturns: '/dashboard/crm/returns',
    crmWorkOrders: '/dashboard/crm/work-orders',
    crmCustomerOnboarding: '/dashboard/crm/customer-onboarding',
    crmOpsDashboard: '/dashboard/crm/ops-dashboard',
    crmTimePeriods: '/dashboard/crm/time-periods',
    crmApprovals: '/dashboard/crm/approvals',
    crmApprovalChains: '/dashboard/crm/approval-chains',
    crmAssignmentRotation: '/dashboard/crm/assignment-rotation',
    crmCommissions: '/dashboard/crm/commissions',
    // ── Web Forms (public capture → contact / lead) ──
    crmWebForms: '/dashboard/crm/webforms',
    crmWebFormNew: '/dashboard/crm/webforms/new',
    crmWebFormEdit: (id: string) => `/dashboard/crm/webforms/${id}/edit`,
    crmWebFormSubmissions: (id: string) => `/dashboard/crm/webforms/${id}/submissions`,
    crmWebFormSubmissionDetail: (formId: string, submissionId: string) =>
      `/dashboard/crm/webforms/${formId}/submissions/${submissionId}`,
    // ── RBAC & Territories ──
    crmTerritories: '/dashboard/crm/territories',
    // ── Procurement ──
    crmVendors: '/dashboard/crm/vendors',
    crmPurchaseOrders: '/dashboard/crm/purchase-orders',
    crmGoodsReceipts: '/dashboard/crm/goods-receipts',
    crmSupplierInvoices: '/dashboard/crm/supplier-invoices',
    // ── Flow A/B Experiments ──
    flowExperiments: '/dashboard/flows/experiments',
    // ── Integrations ──
    videoConferencingSettings: '/dashboard/settings/video-conferencing',
    calendarSettings: '/dashboard/settings/calendar',
    bookingPageSettings: '/dashboard/settings/booking-page',
  },
  schedule: (token: string) => `/schedule/${token}`,
  book: (slug: string) => `/book/${slug}`,
  bookEventType: (slug: string, eventTypeId: string) => `/book/${slug}/${eventTypeId}`,
  portal: {
    auth: '/portal/auth',
    cases: '/portal/cases',
    caseDetail: (id: string) => `/portal/cases/${id}`,
    newCase: '/portal/cases/new',
    invoices: '/portal/invoices',
    orders: '/portal/orders',
    subscriptions: '/portal/subscriptions',
  },
} as const;
