export const ROUTES = {
  auth: {
    login: '/auth/login',
    register: '/auth/register',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
    verifyEmail: '/verify-email',
  },
  public: {
    acceptInvitation: '/accept-invitation',
    approval: (runId: string) => `/approvals/${runId}`,
  },
  dashboard: {
    root: '/dashboard',
    // ── Chat-first primary surfaces (new) ──
    chat: '/dashboard/chat',
    home: '/dashboard/home',
    // ── Existing pages (still reachable, still routed) ──
    // NOTE: setup + onboarding kept for the type, but their routes are
    // commented out in routes.tsx since chat-first replaces them. Don't
    // link to them in new code.
    setup: '/dashboard/setup',
    settings: '/dashboard/settings',
    team: '/dashboard/team',
    intents: '/dashboard/intents',
    intentDetail: (id: string) => `/dashboard/intents/${id}`,
    apiSpecs: '/dashboard/api-specs',
    apiSpecDetail: (id: string) => `/dashboard/api-specs/${id}`,
    apiConnection: '/dashboard/api-connection',
    apiConnectionDetail: (specId: string) => `/dashboard/api-connection/${specId}`,
    intentSuggestions: '/dashboard/intent-suggestions',
    catalog: '/dashboard/catalog',
    businessCatalog: '/dashboard/business-catalog',
    flows: '/dashboard/flows',
    botSettings: '/dashboard/bot-settings',
    channels: '/dashboard/channels',
    testChannel: '/dashboard/test-channel',
    conversations: '/dashboard/conversations',
    campaigns: '/dashboard/campaigns',
    campaignNew: '/dashboard/campaigns/new',
    agents: '/dashboard/agents',
    analytics: '/dashboard/analytics',
    onboarding: '/dashboard/onboarding',
    // ── CRM ──
    crmLeads: '/dashboard/crm/leads',
    crmLeadDetail: (id: string) => `/dashboard/crm/leads/${id}`,
    crmContacts: '/dashboard/crm/contacts',
    crmContactDetail: (id: string) => `/dashboard/crm/contacts/${id}`,
    crmOrganizations: '/dashboard/crm/organizations',
    crmAccounts: '/dashboard/crm/accounts',
    crmDeals: '/dashboard/crm/deals',
    crmDealDetail: (id: string) => `/dashboard/crm/deals/${id}`,
    crmNurture: '/dashboard/crm/nurture',
    crmCampaigns: '/dashboard/crm/campaigns',
    crmAnalytics: '/dashboard/crm/analytics',
    crmSupport: '/dashboard/crm/support',
    crmTasks: '/dashboard/crm/tasks',
    crmQuotes: '/dashboard/crm/quotes',
    crmProposals: '/dashboard/crm/proposals',
    crmInvoices: '/dashboard/crm/invoices',
    crmSubscriptions: '/dashboard/crm/subscriptions',
    crmRenewals: '/dashboard/crm/renewals',
    crmPriceBooks: '/dashboard/crm/price-books',
    crmContracts: '/dashboard/crm/contracts',
    crmOrders: '/dashboard/crm/orders',
    crmMeetings: '/dashboard/crm/meetings',
    crmWorkflows: '/dashboard/crm/workflows',
    crmNps: '/dashboard/crm/nps',
    crmTimeTracking: '/dashboard/crm/time-tracking',
    crmCustomFields: '/dashboard/crm/custom-fields',
    crmDedup: '/dashboard/crm/dedup',
    crmAnnouncements: '/dashboard/crm/announcements',
    crmProcessTasks: '/dashboard/crm/process-tasks',
    crmProcessDefinitions: '/dashboard/crm/process-definitions',
    crmProcessInstances: '/dashboard/crm/process-instances',
    crmEventIngestion: '/dashboard/crm/event-ingestion',
    // ── Flow A/B Experiments ──
    flowExperiments: '/dashboard/flows/experiments',
    // ── Integrations ──
    videoConferencingSettings: '/dashboard/settings/video-conferencing',
    calendarSettings: '/dashboard/settings/calendar',
    bookingPageSettings: '/dashboard/settings/booking-page',
  },
  schedule: (token: string) => `/schedule/${token}`,
  book: (slug: string) => `/book/${slug}`,
  bookEventType: (slug: string, eventTypeId: string) => `/book/${slug}/${eventTypeId}`,
} as const;
