import { Loader2, RefreshCw, Send, X } from 'lucide-react';

interface Props {
  open: boolean;
  onClose: () => void;
  title: string;
  isDrafting: boolean;
  draftText: string;
  onIntroChange: (text: string) => void;
  onRegenerate: () => void;
  isSending: boolean;
  onConfirmSend: () => void;
  confirmLabel?: string;
  /** Read-only structured preview (line items / invoice summary / order table) rendered below the intro. */
  children?: React.ReactNode;
}

/**
 * "AI draft → edit → send" preview modal — shared across Quotes, Orders, and Invoices.
 * The AI drafts a short intro paragraph only; the rep can edit it freely before sending.
 * The structured content (amounts, dates, line items) is rendered read-only via `children`,
 * never generated by the LLM.
 */
export function AiSendPreviewModal({
  open, onClose, title, isDrafting, draftText, onIntroChange, onRegenerate,
  isSending, onConfirmSend, confirmLabel, children,
}: Props) {
  if (!open) return null;

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/50 backdrop-blur-sm px-4">
      <div className="w-full max-w-lg bg-bg-elevated border-thin border-border-subtle rounded-card shadow-2xl max-h-[85vh] flex flex-col">
        <div className="flex items-center justify-between px-5 py-4 border-b border-thin border-border-subtle shrink-0">
          <h3 className="text-sm font-bold text-text-primary">{title}</h3>
          <button onClick={onClose} className="text-text-muted hover:text-text-primary" aria-label="Close">
            <X className="h-4 w-4" />
          </button>
        </div>

        <div className="flex-1 overflow-y-auto px-5 py-4 space-y-4">
          <div>
            <div className="flex items-center justify-between mb-1.5">
              <label className="text-xs font-semibold text-text-muted uppercase tracking-wider">Intro (AI-drafted, editable)</label>
              <button
                onClick={onRegenerate}
                disabled={isDrafting}
                className="flex items-center gap-1 text-xs font-semibold text-text-secondary hover:text-brand disabled:opacity-50 transition-all"
              >
                <RefreshCw className={`w-3 h-3 ${isDrafting ? 'animate-spin' : ''}`} /> Regenerate
              </button>
            </div>
            {isDrafting ? (
              <div className="flex items-center justify-center h-24 rounded-xl border border-border-subtle bg-bg-subtle text-text-muted">
                <Loader2 className="w-4 h-4 animate-spin" />
              </div>
            ) : (
              <textarea
                value={draftText}
                onChange={(e) => onIntroChange(e.target.value)}
                rows={4}
                placeholder="No intro drafted — sending without one."
                className="w-full px-3 py-2 rounded-xl bg-bg-subtle border border-border-subtle text-sm text-text-primary placeholder:text-text-muted focus:outline-none focus:border-border-glow resize-none"
              />
            )}
          </div>

          {children && (
            <div>
              <label className="text-xs font-semibold text-text-muted uppercase tracking-wider mb-1.5 block">Content (unchanged)</label>
              <div className="rounded-xl border border-border-subtle bg-bg-subtle p-3 text-sm text-text-secondary">
                {children}
              </div>
            </div>
          )}
        </div>

        <div className="flex justify-end gap-2 border-t border-thin border-border-subtle px-5 py-3 shrink-0">
          <button
            onClick={onClose}
            className="rounded-sm border-thin border-border-medium px-3.5 py-1.5 text-xs font-semibold text-text-secondary hover:bg-glass-2 hover:text-text-primary transition-colors"
          >
            Cancel
          </button>
          <button
            onClick={onConfirmSend}
            disabled={isSending || isDrafting}
            className="flex items-center gap-1.5 rounded-sm bg-brand px-3.5 py-1.5 text-xs font-bold text-bg hover:bg-brand-light disabled:opacity-50 transition-colors"
          >
            {isSending ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Send className="w-3.5 h-3.5" />}
            {confirmLabel ?? 'Confirm & Send'}
          </button>
        </div>
      </div>
    </div>
  );
}
