export const QUERY_KEYS = {
  auth: ['auth'] as const,
  tenant: ['tenant'] as const,
  channels: ['channels'] as const,
  intents: ['intents'] as const,
  apiSpecs: ['api-specs'] as const,
  specs: ['specs'] as const,
  capability: ['capability'] as const,
  analysis: ['analysis'] as const,
  suggestions: ['suggestions'] as const,
  catalog: ['catalog'] as const,
  flows: ['flows'] as const,
  agents: ['agents'] as const,
  outbound: ['outbound'] as const,
  analytics: ['analytics'] as const,
  testChannel: ['test-channel'] as const,
  voice: ['voice'] as const,
  crm: ['crm'] as const,
  webforms: ['crm', 'webforms'] as const,
  portal: ['portal'] as const,
} as const;
