import { useMemo, useState, type ReactNode } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowDownToLine, Building2, Check, CircleDollarSign, Landmark, Loader2, Plus, ReceiptText, ShieldCheck, Trash2, WalletCards, X } from 'lucide-react';
import { toast } from 'sonner';
import { stylemintCommerceApi } from '../api/stylemint-commerce.api';
import { useAuth } from '@/shared/hooks/useAuth';
import { UserRole } from '@/features/auth/types/auth.types';

type Row = Record<string, unknown>;
const kinds = [{ value: 1, label: 'NIMB Bank' }, { value: 2, label: 'Laxmi Bank' }, { value: 3, label: 'PayPal' }, { value: 4, label: 'eSewa' }];
const list = (value: unknown): Row[] => {
  if (Array.isArray(value)) return value as Row[];
  if (!value || typeof value !== 'object') return [];
  const source = value as Row;
  for (const key of ['items', 'data', 'results', 'entries']) if (Array.isArray(source[key])) return source[key] as Row[];
  return [];
};
const num = (value: unknown) => typeof value === 'number' ? value : Number(value ?? 0) || 0;
const text = (value: unknown) => value == null ? '—' : String(value);
const cash = (value: unknown, currency: unknown = 'CDF') => new Intl.NumberFormat('en-CD', { style: 'currency', currency: text(currency) === '—' ? 'CDF' : text(currency), maximumFractionDigits: 2 }).format(num(value));
const when = (value: unknown) => value ? new Intl.DateTimeFormat('en-CD', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(String(value))) : '—';

export function SellerFinancePage() {
  const { user } = useAuth();
  const canManage = user?.role === UserRole.Owner || user?.role === UserRole.Admin;
  const client = useQueryClient();
  const [destinationOpen, setDestinationOpen] = useState(false);
  const [payoutOpen, setPayoutOpen] = useState(false);
  const [invoiceId, setInvoiceId] = useState<string | null>(null);
  const [destination, setDestination] = useState({ kind: 1, label: '', accountIdentifier: '', branchOrIfsc: '', makeDefault: true });
  const [payout, setPayout] = useState({ amount: '', destinationId: '' });
  const balanceQ = useQuery({ queryKey: ['stylemint-finance', 'balance'], queryFn: stylemintCommerceApi.vendorEarningsBalance });
  const ledgerQ = useQuery({ queryKey: ['stylemint-finance', 'ledger'], queryFn: () => stylemintCommerceApi.vendorEarningsEntries({ pageSize: 50 }) });
  const payoutsQ = useQuery({ queryKey: ['stylemint-finance', 'payouts'], queryFn: () => stylemintCommerceApi.vendorPayouts({ pageSize: 50 }) });
  const destinationsQ = useQuery({ queryKey: ['stylemint-finance', 'destinations'], queryFn: stylemintCommerceApi.vendorPayoutDestinations });
  const invoiceQ = useQuery({ queryKey: ['stylemint-finance', 'invoice', invoiceId], queryFn: () => stylemintCommerceApi.vendorPayoutInvoice(invoiceId!), enabled: Boolean(invoiceId) });
  const balance = balanceQ.data ?? {};
  const ledger = useMemo(() => list(ledgerQ.data), [ledgerQ.data]);
  const payouts = useMemo(() => list(payoutsQ.data), [payoutsQ.data]);
  const destinations = useMemo(() => list(destinationsQ.data), [destinationsQ.data]);
  const refresh = () => client.invalidateQueries({ queryKey: ['stylemint-finance'] });
  const requestPayout = useMutation({ mutationFn: () => stylemintCommerceApi.requestVendorPayout({ amount: Number(payout.amount), destinationId: payout.destinationId, destinationKind: num(destinations.find((item) => text(item.id) === payout.destinationId)?.kind) }), onSuccess: () => { toast.success('Payout request submitted'); setPayoutOpen(false); setPayout({ amount: '', destinationId: '' }); refresh(); }, onError: () => toast.error('Payout request failed') });
  const addDestination = useMutation({ mutationFn: () => stylemintCommerceApi.createVendorPayoutDestination(destination), onSuccess: () => { toast.success('Payment destination added'); setDestinationOpen(false); setDestination({ kind: 1, label: '', accountIdentifier: '', branchOrIfsc: '', makeDefault: true }); refresh(); }, onError: () => toast.error('Could not add payment destination') });
  const setDefault = useMutation({ mutationFn: stylemintCommerceApi.setDefaultVendorPayoutDestination, onSuccess: () => { toast.success('Default destination updated'); refresh(); } });
  const remove = useMutation({ mutationFn: stylemintCommerceApi.deleteVendorPayoutDestination, onSuccess: () => { toast.success('Payment destination removed'); refresh(); } });
  const loading = balanceQ.isLoading || ledgerQ.isLoading || payoutsQ.isLoading || destinationsQ.isLoading;
  const failed = balanceQ.isError || ledgerQ.isError || payoutsQ.isError || destinationsQ.isError;
  const currency = balance.currency ?? 'CDF';
  const available = balance.availableAmount ?? balance.available ?? balance.balance ?? 0;

  return <div className="mx-auto max-w-[1500px] space-y-6 p-4 sm:p-6">
    <section className="relative overflow-hidden rounded-[2rem] bg-slate-950 px-6 py-9 text-white shadow-2xl sm:px-10"><div className="absolute -right-20 -top-24 h-80 w-80 rounded-full bg-emerald-400/20 blur-3xl" /><div className="relative grid gap-8 lg:grid-cols-[1.35fr_1fr] lg:items-end"><div><div className="mb-4 inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-3 py-1 text-xs font-semibold uppercase tracking-[.2em] text-emerald-200"><ShieldCheck className="h-4 w-4" /> Seller money desk</div><h1 className="max-w-3xl text-3xl font-semibold tracking-tight sm:text-5xl">Every sale, settlement and payout. One trusted workspace.</h1><p className="mt-4 max-w-2xl text-slate-300">Reconcile earnings, audit the ledger, manage verified accounts and request payouts without leaving Lead360.</p></div><div className="rounded-3xl border border-white/10 bg-white/10 p-5 backdrop-blur-xl"><p className="text-xs font-semibold uppercase tracking-[.18em] text-slate-300">Available to withdraw</p><p className="mt-2 text-4xl font-semibold">{cash(available, currency)}</p><div className="mt-5 flex gap-3"><button disabled={!canManage || destinations.length === 0} onClick={() => setPayoutOpen(true)} className="inline-flex flex-1 items-center justify-center gap-2 rounded-xl bg-emerald-400 px-4 py-3 text-sm font-bold text-slate-950 disabled:opacity-40"><ArrowDownToLine className="h-4 w-4" /> Request payout</button><button disabled={!canManage} onClick={() => setDestinationOpen(true)} className="rounded-xl border border-white/15 bg-white/10 p-3 disabled:opacity-40"><Plus className="h-5 w-5" /></button></div></div></div></section>
    {failed && <div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">Seller finance data could not be loaded. Check Stylemint connectivity and try again.</div>}
    {loading ? <div className="flex h-56 items-center justify-center"><Loader2 className="h-8 w-8 animate-spin text-emerald-600" /></div> : <>
      <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{([['Available', available, WalletCards], ['Pending', balance.pendingAmount ?? balance.pending ?? 0, CircleDollarSign], ['Lifetime earned', balance.lifetimeEarnings ?? balance.totalEarned ?? 0, Landmark], ['Paid out', balance.totalPaidOut ?? balance.paidOut ?? 0, Check]] as const).map(([label, value, Icon]) => <article key={label} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><p className="text-sm font-medium text-slate-500">{label}</p><span className="rounded-xl bg-emerald-50 p-2 text-emerald-700"><Icon className="h-5 w-5" /></span></div><p className="mt-4 text-2xl font-bold text-slate-950">{cash(value, currency)}</p></article>)}</section>
      <section className="grid gap-6 xl:grid-cols-[1.4fr_1fr]"><Panel title="Earnings ledger" subtitle="Auditable movement of seller funds." icon={<ReceiptText className="h-5 w-5" />}><div className="divide-y divide-slate-100">{ledger.length === 0 ? <Empty text="No ledger entries yet" /> : ledger.map((item, index) => <div key={text(item.id ?? index)} className="grid grid-cols-[1fr_auto] gap-4 p-5"><div><p className="font-semibold text-slate-900">{text(item.description ?? item.type ?? item.entryType)}</p><p className="mt-1 text-xs text-slate-500">{when(item.createdUtc ?? item.occurredUtc ?? item.date)}</p></div><p className={`font-bold ${num(item.amount) >= 0 ? 'text-emerald-700' : 'text-rose-600'}`}>{cash(item.amount, item.currency ?? currency)}</p></div>)}</div></Panel>
      <Panel title="Payment destinations" subtitle="Verified accounts that can receive payouts."><div className="space-y-3 p-4">{destinations.length === 0 ? <Empty text="Add a destination to request payouts" /> : destinations.map((item) => <div key={text(item.id)} className="rounded-2xl border border-slate-200 p-4"><div className="flex items-start justify-between gap-3"><div className="flex gap-3"><span className="rounded-xl bg-slate-100 p-2"><Building2 className="h-5 w-5" /></span><div><p className="font-semibold text-slate-900">{text(item.label)} {item.isDefault === true && <span className="ml-1 rounded-full bg-emerald-100 px-2 py-0.5 text-[10px] uppercase text-emerald-700">Default</span>}</p><p className="text-sm text-slate-500">{text(item.accountIdentifierMasked)}</p><p className="text-xs text-slate-400">{kinds.find((kind) => kind.value === num(item.kind))?.label ?? text(item.kind)} · {item.verified === true ? 'Verified' : 'Pending verification'}</p></div></div>{canManage && <button onClick={() => remove.mutate(text(item.id))} className="p-2 text-slate-400 hover:text-rose-600"><Trash2 className="h-4 w-4" /></button>}</div>{canManage && !item.isDefault && <button onClick={() => setDefault.mutate(text(item.id))} className="mt-3 text-xs font-semibold text-emerald-700">Make default</button>}</div>)}</div></Panel></section>
      <Panel title="Payout history" subtitle="Settlement status and invoice details."><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-6 py-3">Reference</th><th className="px-6 py-3">Requested</th><th className="px-6 py-3">Destination</th><th className="px-6 py-3">Status</th><th className="px-6 py-3 text-right">Amount</th></tr></thead><tbody className="divide-y divide-slate-100">{payouts.length === 0 ? <tr><td colSpan={5}><Empty text="No payouts requested" /></td></tr> : payouts.map((item) => <tr key={text(item.id)} onClick={() => setInvoiceId(text(item.id))} className="cursor-pointer hover:bg-slate-50"><td className="px-6 py-4 font-semibold">{text(item.reference ?? item.id)}</td><td className="px-6 py-4 text-slate-500">{when(item.requestedUtc ?? item.createdUtc)}</td><td className="px-6 py-4 text-slate-500">{kinds.find((kind) => kind.value === num(item.destination))?.label ?? text(item.destination)}</td><td className="px-6 py-4"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold">{text(item.status ?? item.state)}</span></td><td className="px-6 py-4 text-right font-bold">{cash(item.amount ?? item.requestedAmount, item.currency ?? currency)}</td></tr>)}</tbody></table></div></Panel>
    </>}
    {destinationOpen && <Modal title="Add payment destination" close={() => setDestinationOpen(false)}><div className="space-y-4"><FieldSelect label="Destination type" value={destination.kind} change={(value) => setDestination({ ...destination, kind: Number(value) })} options={kinds} /><Field label="Account label" value={destination.label} change={(value) => setDestination({ ...destination, label: value })} placeholder="Main settlement account" /><Field label="Account, email or wallet ID" value={destination.accountIdentifier} change={(value) => setDestination({ ...destination, accountIdentifier: value })} placeholder="Receiving identifier" /><Field label="Branch / IFSC" value={destination.branchOrIfsc} change={(value) => setDestination({ ...destination, branchOrIfsc: value })} placeholder="Optional" /><label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={destination.makeDefault} onChange={(event) => setDestination({ ...destination, makeDefault: event.target.checked })} /> Make default</label><Action disabled={!destination.label || !destination.accountIdentifier || addDestination.isPending} click={() => addDestination.mutate()}>Add destination</Action></div></Modal>}
    {payoutOpen && <Modal title="Request payout" close={() => setPayoutOpen(false)}><div className="space-y-4"><Field label="Amount" type="number" value={payout.amount} change={(value) => setPayout({ ...payout, amount: value })} placeholder="0.00" /><FieldSelect label="Payment destination" value={payout.destinationId} change={(value) => setPayout({ ...payout, destinationId: String(value) })} options={destinations.map((item) => ({ value: text(item.id), label: `${text(item.label)} · ${text(item.accountIdentifierMasked)}` }))} /><Action disabled={!payout.destinationId || Number(payout.amount) <= 0 || requestPayout.isPending} click={() => requestPayout.mutate()}>Submit payout request</Action></div></Modal>}
    {invoiceId && <Modal title="Payout invoice" close={() => setInvoiceId(null)}>{invoiceQ.isLoading ? <Loader2 className="mx-auto h-7 w-7 animate-spin" /> : <div className="space-y-3 rounded-2xl bg-slate-50 p-4">{Object.entries(invoiceQ.data ?? {}).map(([key, value]) => <div key={key} className="flex justify-between gap-5 border-b border-slate-200 pb-2 text-sm last:border-0"><span className="text-slate-500">{key.replace(/([A-Z])/g, ' $1')}</span><span className="text-right font-semibold">{typeof value === 'object' ? JSON.stringify(value) : text(value)}</span></div>)}</div>}</Modal>}
  </div>;
}

function Panel({ title, subtitle, icon, children }: { title: string; subtitle: string; icon?: ReactNode; children: ReactNode }) { return <section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 p-6"><div><h2 className="text-lg font-bold text-slate-950">{title}</h2><p className="text-sm text-slate-500">{subtitle}</p></div>{icon}</div>{children}</section>; }
function Empty({ text: value }: { text: string }) { return <div className="p-8 text-center text-sm text-slate-500">{value}</div>; }
function Modal({ title, close, children }: { title: string; close: () => void; children: ReactNode }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4 backdrop-blur-sm"><div className="w-full max-w-lg rounded-3xl bg-white p-6 shadow-2xl"><div className="mb-5 flex items-center justify-between"><h2 className="text-xl font-bold">{title}</h2><button onClick={close} className="rounded-lg p-2 hover:bg-slate-100"><X className="h-5 w-5" /></button></div>{children}</div></div>; }
function Field({ label, value, change, placeholder, type = 'text' }: { label: string; value: string; change: (value: string) => void; placeholder: string; type?: string }) { return <label className="block text-sm font-semibold text-slate-700">{label}<input type={type} value={value} onChange={(event) => change(event.target.value)} placeholder={placeholder} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 font-normal outline-none focus:border-emerald-500" /></label>; }
function FieldSelect({ label, value, change, options }: { label: string; value: string | number; change: (value: string | number) => void; options: Array<{ value: string | number; label: string }> }) { return <label className="block text-sm font-semibold text-slate-700">{label}<select value={value} onChange={(event) => change(event.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 bg-white px-4 py-3 font-normal"><option value="">Select…</option>{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label>; }
function Action({ children, click, disabled }: { children: ReactNode; click: () => void; disabled?: boolean }) { return <button disabled={disabled} onClick={click} className="w-full rounded-xl bg-slate-950 px-4 py-3 text-sm font-bold text-white hover:bg-emerald-700 disabled:opacity-40">{children}</button>; }

export const Component = SellerFinancePage;
